import { BoardConfig } from "./models";

// Oldest Game
export const oldestGame: BoardConfig = {
  rows: 11,
  columns: 10,
  target: [
    { row: 10, column: 9 },
    { row: 10, column: 10 },
    { row: 11, column: 9 },
    { row: 11, column: 10 },
  ],
  masterBlock: [
    { row: 4, column: 5 },
    { row: 4, column: 6 },
    { row: 5, column: 5 },
    { row: 5, column: 6 },
  ],
  blocks: [
    [
      { row: 4, column: 4 },
      { row: 5, column: 4 },
    ],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [{ row: 6, column: 4 }],
    [{ row: 6, column: 5 }],
    [{ row: 6, column: 6 }],
    [{ row: 6, column: 7 }],
    [{ row: 7, column: 4 }],
    [{ row: 7, column: 5 }],
    [{ row: 7, column: 6 }],
    [{ row: 7, column: 7 }],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 7 }],
  ],
  walls: [
    [
      { row: 9, column: 4 },
      { row: 9, column: 3 },
      { row: 8, column: 3 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 3, column: 4 },
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
      { row: 6, column: 8 },
      { row: 7, column: 8 },
      { row: 8, column: 8 },
      { row: 9, column: 8 },
      { row: 9, column: 7 },
    ],
  ],
  gates: [
    [
      { row: 9, column: 5 },
      { row: 9, column: 6 },
    ],
  ],
};

export const oldestGame2: BoardConfig = {
  rows: 11,
  columns: 10,
  target: [
    { row: 10, column: 9 },
    { row: 10, column: 10 },
    { row: 11, column: 9 },
    { row: 11, column: 10 },
  ],
  masterBlock: [
    { row: 4, column: 5 },
    { row: 4, column: 6 },
    { row: 5, column: 5 },
    { row: 5, column: 6 },
  ],
  blocks: [
    [
      { row: 4, column: 4 },
      { row: 5, column: 4 },
    ],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [
      { row: 6, column: 4 },
      { row: 7, column: 4 },
    ],
    [{ row: 6, column: 5 }],
    [{ row: 6, column: 6 }],
    [{ row: 6, column: 7 }],
    [{ row: 7, column: 5 }],
    [{ row: 7, column: 6 }],
    [{ row: 7, column: 7 }],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 7 }],
  ],
  walls: [
    [
      { row: 9, column: 4 },
      { row: 9, column: 3 },
      { row: 8, column: 3 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 3, column: 4 },
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
      { row: 6, column: 8 },
      { row: 7, column: 8 },
      { row: 8, column: 8 },
      { row: 9, column: 8 },
      { row: 9, column: 7 },
    ],
  ],
  gates: [
    [
      { row: 9, column: 5 },
      { row: 9, column: 6 },
    ],
  ],
};

export const oldestGame3: BoardConfig = {
  rows: 11,
  columns: 10,
  target: [
    { row: 10, column: 9 },
    { row: 10, column: 10 },
    { row: 11, column: 9 },
    { row: 11, column: 10 },
  ],
  masterBlock: [
    { row: 4, column: 5 },
    { row: 4, column: 6 },
    { row: 5, column: 5 },
    { row: 5, column: 6 },
  ],
  blocks: [
    [
      { row: 4, column: 4 },
      { row: 5, column: 4 },
    ],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [{ row: 6, column: 4 }],
    [
      { row: 6, column: 5 },
      { row: 6, column: 6 },
    ],
    [{ row: 6, column: 7 }],
    [{ row: 7, column: 4 }],
    [{ row: 7, column: 5 }],
    [{ row: 7, column: 6 }],
    [{ row: 7, column: 7 }],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 7 }],
  ],
  walls: [
    [
      { row: 9, column: 4 },
      { row: 9, column: 3 },
      { row: 8, column: 3 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 3, column: 4 },
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
      { row: 6, column: 8 },
      { row: 7, column: 8 },
      { row: 8, column: 8 },
      { row: 9, column: 8 },
      { row: 9, column: 7 },
    ],
  ],
  gates: [
    [
      { row: 9, column: 5 },
      { row: 9, column: 6 },
    ],
  ],
};

export const oldestGame4: BoardConfig = {
  rows: 11,
  columns: 10,
  target: [
    { row: 10, column: 9 },
    { row: 10, column: 10 },
    { row: 11, column: 9 },
    { row: 11, column: 10 },
  ],
  masterBlock: [
    { row: 4, column: 5 },
    { row: 4, column: 6 },
    { row: 5, column: 5 },
    { row: 5, column: 6 },
  ],
  blocks: [
    [
      { row: 4, column: 4 },
      { row: 5, column: 4 },
    ],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [
      { row: 6, column: 4 },
      { row: 7, column: 4 },
    ],
    [{ row: 6, column: 5 }],
    [{ row: 6, column: 6 }],
    [
      { row: 6, column: 7 },
      { row: 7, column: 7 },
    ],
    [{ row: 7, column: 5 }],
    [{ row: 7, column: 6 }],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 7 }],
  ],
  walls: [
    [
      { row: 9, column: 4 },
      { row: 9, column: 3 },
      { row: 8, column: 3 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 3, column: 4 },
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
      { row: 6, column: 8 },
      { row: 7, column: 8 },
      { row: 8, column: 8 },
      { row: 9, column: 8 },
      { row: 9, column: 7 },
    ],
  ],
  gates: [
    [
      { row: 9, column: 5 },
      { row: 9, column: 6 },
    ],
  ],
};

export const oldestGame5: BoardConfig = {
  rows: 11,
  columns: 10,
  target: [
    { row: 10, column: 9 },
    { row: 10, column: 10 },
    { row: 11, column: 9 },
    { row: 11, column: 10 },
  ],
  masterBlock: [
    { row: 4, column: 5 },
    { row: 4, column: 6 },
    { row: 5, column: 5 },
    { row: 5, column: 6 },
  ],
  blocks: [
    [
      { row: 4, column: 4 },
      { row: 5, column: 4 },
    ],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [
      { row: 6, column: 4 },
      { row: 7, column: 4 },
    ],
    [
      { row: 6, column: 5 },
      { row: 6, column: 6 },
    ],
    [{ row: 6, column: 7 }],
    [{ row: 7, column: 5 }],
    [{ row: 7, column: 6 }],
    [{ row: 7, column: 7 }],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 7 }],
  ],
  walls: [
    [
      { row: 9, column: 4 },
      { row: 9, column: 3 },
      { row: 8, column: 3 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 3, column: 4 },
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
      { row: 6, column: 8 },
      { row: 7, column: 8 },
      { row: 8, column: 8 },
      { row: 9, column: 8 },
      { row: 9, column: 7 },
    ],
  ],
  gates: [
    [
      { row: 9, column: 5 },
      { row: 9, column: 6 },
    ],
  ],
};

export const oldestGame6: BoardConfig = {
  rows: 11,
  columns: 10,
  target: [
    { row: 10, column: 9 },
    { row: 10, column: 10 },
    { row: 11, column: 9 },
    { row: 11, column: 10 },
  ],
  masterBlock: [
    { row: 4, column: 5 },
    { row: 4, column: 6 },
    { row: 5, column: 5 },
    { row: 5, column: 6 },
  ],
  blocks: [
    [
      { row: 4, column: 4 },
      { row: 5, column: 4 },
    ],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [
      { row: 6, column: 4 },
      { row: 7, column: 4 },
    ],
    [
      { row: 6, column: 5 },
      { row: 6, column: 6 },
    ],
    [
      { row: 6, column: 7 },
      { row: 7, column: 7 },
    ],
    [{ row: 7, column: 5 }],
    [{ row: 7, column: 6 }],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 7 }],
  ],
  walls: [
    [
      { row: 9, column: 4 },
      { row: 9, column: 3 },
      { row: 8, column: 3 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 3, column: 4 },
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
      { row: 6, column: 8 },
      { row: 7, column: 8 },
      { row: 8, column: 8 },
      { row: 9, column: 8 },
      { row: 9, column: 7 },
    ],
  ],
  gates: [
    [
      { row: 9, column: 5 },
      { row: 9, column: 6 },
    ],
  ],
};

export const agatka: BoardConfig = {
  rows: 9,
  columns: 11,
  target: [
    { row: 8, column: 1 },
    { row: 8, column: 2 },
    { row: 9, column: 1 },
  ],
  masterBlock: [
    { row: 4, column: 4 },
    { row: 4, column: 5 },
    { row: 5, column: 4 },
  ],
  blocks: [
    [{ row: 1, column: 1 }],
    [{ row: 2, column: 1 }],
    [
      { row: 1, column: 2 },
      { row: 1, column: 3 },
      { row: 1, column: 4 },
      { row: 1, column: 5 },
      { row: 2, column: 2 },
      { row: 2, column: 3 },
      { row: 2, column: 4 },
      { row: 2, column: 5 },
    ],
    [
      { row: 1, column: 6 },
      { row: 1, column: 7 },
      { row: 1, column: 8 },
      { row: 1, column: 9 },
      { row: 1, column: 10 },
    ],
    [{ row: 1, column: 11 }],
    [
      { row: 2, column: 6 },
      { row: 2, column: 7 },
      { row: 2, column: 8 },
    ],
    [
      { row: 2, column: 10 },
      { row: 2, column: 11 },
    ],
    [{ row: 3, column: 10 }],
    [
      { row: 5, column: 1 },
      { row: 6, column: 1 },
    ],
    [
      { row: 3, column: 2 },
      { row: 4, column: 2 },
      { row: 5, column: 2 },
      { row: 6, column: 2 },
      { row: 7, column: 2 },
      { row: 8, column: 2 },
      { row: 9, column: 2 },
    ],
    [
      { row: 9, column: 3 },
      { row: 9, column: 4 },
    ],
    [{ row: 8, column: 5 }],
    [{ row: 9, column: 7 }],
    [{ row: 8, column: 9 }],
    [
      { row: 4, column: 6 },
      { row: 4, column: 7 },
    ],
    [{ row: 4, column: 8 }],
    [
      { row: 5, column: 5 },
      { row: 5, column: 6 },
    ],
    [{ row: 5, column: 7 }],
    [{ row: 5, column: 8 }],
    [{ row: 6, column: 4 }],
    [{ row: 6, column: 5 }],
    [{ row: 6, column: 6 }],
  ],
  walls: [
    [
      { row: 3, column: 7 },
      { row: 3, column: 6 },
      { row: 3, column: 5 },
      { row: 3, column: 4 },
      { row: 3, column: 3 },
      { row: 4, column: 3 },
      { row: 5, column: 3 },
      { row: 6, column: 3 },
      { row: 7, column: 3 },
      { row: 7, column: 4 },
      { row: 7, column: 5 },
      { row: 7, column: 6 },
      { row: 7, column: 7 },
      { row: 7, column: 8 },
      { row: 7, column: 9 },
      { row: 6, column: 9 },
      { row: 5, column: 9 },
    ],
  ],
  gates: [
    [
      { row: 3, column: 8 },
      { row: 3, column: 9 },
      { row: 4, column: 9 },
    ],
  ],
};

export const doggie: BoardConfig = {
  rows: 15,
  columns: 18,
  target: [
    { row: 1, column: 1 },
    { row: 1, column: 2 },
    { row: 2, column: 2 },
    { row: 3, column: 1 },
    { row: 3, column: 2 },
    { row: 3, column: 3 },
    { row: 3, column: 4 },
    { row: 4, column: 3 },
    { row: 4, column: 4 },
  ],
  masterBlock: [
    { row: 6, column: 7 },
    { row: 6, column: 8 },
    { row: 7, column: 8 },
    { row: 8, column: 7 },
    { row: 8, column: 8 },
    { row: 8, column: 9 },
    { row: 8, column: 10 },
    { row: 9, column: 9 },
    { row: 9, column: 10 },
  ],
  blocks: [
    [{ row: 6, column: 6 }],
    [
      { row: 7, column: 6 },
      { row: 7, column: 7 },
    ],
    [{ row: 8, column: 6 }],
    [{ row: 9, column: 6 }],
    [{ row: 9, column: 7 }],
    [{ row: 9, column: 8 }],
    [{ row: 10, column: 6 }],
    [{ row: 10, column: 7 }],
    [{ row: 10, column: 8 }],
    [
      { row: 6, column: 9 },
      { row: 7, column: 9 },
    ],
    [
      { row: 6, column: 10 },
      { row: 6, column: 11 },
      { row: 6, column: 12 },
    ],
    [{ row: 6, column: 13 }],
    [{ row: 7, column: 10 }],
    [{ row: 7, column: 11 }],
    [{ row: 7, column: 12 }],
    [{ row: 7, column: 13 }],
    [{ row: 8, column: 11 }],
    [{ row: 8, column: 12 }],
    [{ row: 8, column: 13 }],
    [{ row: 9, column: 11 }],
    [{ row: 9, column: 12 }],
    [{ row: 9, column: 13 }],
  ],
  walls: [
    [
      { row: 11, column: 11 },
      { row: 11, column: 10 },
      { row: 11, column: 9 },
      { row: 11, column: 8 },
      { row: 11, column: 7 },
      { row: 11, column: 6 },
      { row: 11, column: 5 },
      { row: 10, column: 5 },
      { row: 9, column: 5 },
      { row: 8, column: 5 },
      { row: 7, column: 5 },
      { row: 6, column: 5 },
      { row: 5, column: 5 },
      { row: 5, column: 6 },
      { row: 5, column: 7 },
      { row: 5, column: 8 },
      { row: 5, column: 9 },
      { row: 5, column: 10 },
      { row: 5, column: 11 },
      { row: 5, column: 12 },
      { row: 5, column: 13 },
      { row: 5, column: 14 },
      { row: 6, column: 14 },
      { row: 7, column: 14 },
      { row: 8, column: 14 },
      { row: 9, column: 14 },
    ],
  ],
  gates: [
    [
      { row: 10, column: 14 },
      { row: 11, column: 14 },
      { row: 11, column: 13 },
      { row: 11, column: 12 },
    ],
  ],
};

export const success: BoardConfig = {
  rows: 8,
  columns: 11,
  target: [
    { row: 1, column: 1 },
    { row: 1, column: 2 },
  ],
  masterBlock: [
    { row: 3, column: 4 },
    { row: 3, column: 5 },
  ],
  blocks: [
    [
      { row: 4, column: 1 },
      { row: 4, column: 2 },
      { row: 5, column: 1 },
      { row: 5, column: 2 },
    ],
    [{ row: 1, column: 11 }],
    [
      { row: 3, column: 6 },
      { row: 3, column: 7 },
    ],
    [{ row: 3, column: 8 }],
    [{ row: 4, column: 4 }],
    [{ row: 4, column: 5 }],
    [{ row: 4, column: 6 }],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [
      { row: 4, column: 8 },
      { row: 5, column: 8 },
    ],
    [{ row: 5, column: 4 }],
    [{ row: 5, column: 5 }],
    [
      { row: 5, column: 6 },
      { row: 6, column: 6 },
    ],
    [
      { row: 6, column: 4 },
      { row: 6, column: 5 },
    ],
  ],
  walls: [
    [
      { row: 6, column: 9 },
      { row: 7, column: 9 },
      { row: 7, column: 8 },
      { row: 7, column: 7 },
      { row: 7, column: 6 },
      { row: 7, column: 5 },
      { row: 7, column: 4 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 2, column: 3 },
      { row: 2, column: 4 },
      { row: 2, column: 5 },
      { row: 2, column: 6 },
      { row: 2, column: 7 },
      { row: 2, column: 8 },
      { row: 2, column: 9 },
      { row: 3, column: 9 },
      { row: 4, column: 9 },
    ],
  ],
  gates: [[{ row: 5, column: 9 }]],
};

export const bone: BoardConfig = {
  rows: 12,
  columns: 8,
  target: [
    { row: 1, column: 1 },
    { row: 2, column: 1 },
    { row: 3, column: 1 },
  ],
  masterBlock: [
    { row: 5, column: 6 },
    { row: 6, column: 6 },
    { row: 7, column: 6 },
  ],
  blocks: [
    [{ row: 3, column: 2 }],
    [{ row: 5, column: 3 }],
    [{ row: 5, column: 4 }],
    [{ row: 5, column: 5 }],
    [
      { row: 6, column: 4 },
      { row: 6, column: 5 },
    ],
    [
      { row: 7, column: 4 },
      { row: 7, column: 5 },
    ],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 5 }],
    [{ row: 8, column: 6 }],
  ],
  walls: [
    [
      { row: 9, column: 3 },
      { row: 9, column: 2 },
      { row: 8, column: 2 },
      { row: 7, column: 2 },
      { row: 6, column: 2 },
      { row: 5, column: 2 },
      { row: 4, column: 2 },
      { row: 4, column: 3 },
      { row: 4, column: 4 },
      { row: 4, column: 5 },
      { row: 4, column: 6 },
      { row: 4, column: 7 },
      { row: 5, column: 7 },
      { row: 6, column: 7 },
      { row: 7, column: 7 },
      { row: 8, column: 7 },
      { row: 9, column: 7 },
      { row: 9, column: 6 },
      { row: 9, column: 5 },
    ],
  ],
  gates: [[{ row: 9, column: 4 }]],
};

export const fortune: BoardConfig = {
  rows: 14,
  columns: 10,
  target: [
    { row: 1, column: 1 },
    { row: 1, column: 2 },
    { row: 2, column: 1 },
    { row: 3, column: 1 },
  ],
  masterBlock: [
    { row: 8, column: 4 },
    { row: 8, column: 5 },
    { row: 9, column: 4 },
    { row: 10, column: 4 },
  ],
  blocks: [
    [
      { row: 1, column: 8 },
      { row: 1, column: 9 },
      { row: 1, column: 10 },
    ],
    [
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
    ],
    [{ row: 5, column: 4 }],
    [{ row: 5, column: 5 }],
    [
      { row: 6, column: 4 },
      { row: 6, column: 5 },
      { row: 7, column: 4 },
      { row: 7, column: 5 },
    ],
    [
      { row: 6, column: 6 },
      { row: 7, column: 6 },
    ],
    [
      { row: 8, column: 6 },
      { row: 8, column: 7 },
    ],
    [{ row: 9, column: 5 }],
    [{ row: 9, column: 6 }],
    [
      { row: 9, column: 7 },
      { row: 10, column: 7 },
    ],
    [
      { row: 10, column: 5 },
      { row: 10, column: 6 },
    ],
    [
      { row: 11, column: 1 },
      { row: 12, column: 1 },
    ],
    [
      { row: 10, column: 10 },
      { row: 11, column: 10 },
      { row: 12, column: 10 },
    ],
    [{ row: 14, column: 2 }],
  ],
  walls: [
    [
      { row: 4, column: 6 },
      { row: 4, column: 5 },
      { row: 4, column: 4 },
      { row: 4, column: 3 },
      { row: 5, column: 3 },
      { row: 6, column: 3 },
      { row: 7, column: 3 },
      { row: 8, column: 3 },
      { row: 9, column: 3 },
      { row: 10, column: 3 },
      { row: 11, column: 3 },
      { row: 11, column: 4 },
      { row: 11, column: 5 },
      { row: 11, column: 6 },
      { row: 11, column: 7 },
      { row: 11, column: 8 },
      { row: 10, column: 8 },
      { row: 9, column: 8 },
      { row: 8, column: 8 },
      { row: 7, column: 8 },
      { row: 6, column: 8 },
    ],
  ],
  gates: [
    [
      { row: 4, column: 7 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
    ],
  ],
};

export const sunshine: BoardConfig = {
  rows: 27,
  columns: 27,
  target: [
    { row: 1, column: 13 },
    { row: 1, column: 14 },
    { row: 1, column: 15 },
    { row: 2, column: 12 },
    { row: 2, column: 13 },
    { row: 2, column: 15 },
    { row: 2, column: 16 },
    { row: 3, column: 12 },
    { row: 3, column: 16 },
    { row: 4, column: 12 },
    { row: 4, column: 13 },
    { row: 4, column: 15 },
    { row: 4, column: 16 },
    { row: 5, column: 13 },
    { row: 5, column: 14 },
    { row: 5, column: 15 },
  ],
  masterBlock: [
    { row: 7, column: 13 },
    { row: 7, column: 14 },
    { row: 7, column: 15 },
    { row: 8, column: 12 },
    { row: 8, column: 13 },
    { row: 8, column: 15 },
    { row: 8, column: 16 },
    { row: 9, column: 12 },
    { row: 9, column: 16 },
    { row: 10, column: 12 },
    { row: 10, column: 13 },
    { row: 10, column: 15 },
    { row: 10, column: 16 },
    { row: 11, column: 13 },
    { row: 11, column: 14 },
    { row: 11, column: 15 },
  ],
  blocks: [
    [
      { row: 1, column: 1 },
      { row: 1, column: 2 },
      { row: 2, column: 1 },
      { row: 2, column: 2 },
    ],
    [
      { row: 1, column: 3 },
      { row: 2, column: 3 },
    ],
    [
      { row: 1, column: 4 },
      { row: 1, column: 5 },
      { row: 2, column: 4 },
      { row: 2, column: 5 },
    ],
    [
      { row: 3, column: 1 },
      { row: 3, column: 2 },
    ],
    [
      { row: 3, column: 4 },
      { row: 3, column: 5 },
    ],
    [
      { row: 4, column: 1 },
      { row: 4, column: 2 },
      { row: 5, column: 1 },
      { row: 5, column: 2 },
    ],
    [
      { row: 4, column: 3 },
      { row: 5, column: 3 },
    ],
    [
      { row: 4, column: 4 },
      { row: 4, column: 5 },
      { row: 5, column: 4 },
      { row: 5, column: 5 },
    ],
    [
      { row: 1, column: 6 },
      { row: 1, column: 7 },
      { row: 1, column: 8 },
      { row: 1, column: 9 },
      { row: 1, column: 10 },
      { row: 2, column: 6 },
      { row: 2, column: 7 },
      { row: 2, column: 8 },
      { row: 2, column: 9 },
      { row: 2, column: 10 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 3, column: 9 },
      { row: 3, column: 10 },
      { row: 4, column: 6 },
      { row: 4, column: 7 },
      { row: 4, column: 8 },
      { row: 4, column: 9 },
      { row: 4, column: 10 },
      { row: 5, column: 6 },
      { row: 5, column: 7 },
      { row: 5, column: 8 },
      { row: 5, column: 9 },
      { row: 5, column: 10 },
    ],
    [
      { row: 1, column: 12 },
      { row: 1, column: 13 },
      { row: 2, column: 12 },
      { row: 2, column: 13 },
    ],
    [
      { row: 1, column: 14 },
      { row: 2, column: 14 },
    ],
    [
      { row: 1, column: 15 },
      { row: 1, column: 16 },
      { row: 2, column: 15 },
      { row: 2, column: 16 },
    ],
    [
      { row: 3, column: 12 },
      { row: 3, column: 13 },
    ],
    [
      { row: 3, column: 15 },
      { row: 3, column: 16 },
    ],
    [
      { row: 4, column: 12 },
      { row: 4, column: 13 },
      { row: 5, column: 12 },
      { row: 5, column: 13 },
    ],
    [
      { row: 4, column: 14 },
      { row: 5, column: 14 },
    ],
    [
      { row: 4, column: 15 },
      { row: 4, column: 16 },
      { row: 5, column: 15 },
      { row: 5, column: 16 },
    ],
    [
      { row: 1, column: 18 },
      { row: 1, column: 19 },
      { row: 1, column: 20 },
      { row: 1, column: 21 },
      { row: 1, column: 22 },
      { row: 2, column: 18 },
      { row: 2, column: 19 },
      { row: 2, column: 20 },
      { row: 2, column: 21 },
      { row: 2, column: 22 },
      { row: 3, column: 18 },
      { row: 3, column: 19 },
      { row: 3, column: 20 },
      { row: 3, column: 21 },
      { row: 3, column: 22 },
      { row: 4, column: 18 },
      { row: 4, column: 19 },
      { row: 4, column: 20 },
      { row: 4, column: 21 },
      { row: 4, column: 22 },
      { row: 5, column: 18 },
      { row: 5, column: 19 },
      { row: 5, column: 20 },
      { row: 5, column: 21 },
      { row: 5, column: 22 },
    ],
    [
      { row: 1, column: 23 },
      { row: 1, column: 24 },
      { row: 2, column: 23 },
      { row: 2, column: 24 },
    ],
    [
      { row: 1, column: 25 },
      { row: 2, column: 25 },
    ],
    [
      { row: 1, column: 26 },
      { row: 1, column: 27 },
      { row: 2, column: 26 },
      { row: 2, column: 27 },
    ],
    [
      { row: 3, column: 23 },
      { row: 3, column: 24 },
    ],
    [
      { row: 3, column: 26 },
      { row: 3, column: 27 },
    ],
    [
      { row: 4, column: 23 },
      { row: 4, column: 24 },
      { row: 5, column: 23 },
      { row: 5, column: 24 },
    ],
    [
      { row: 4, column: 25 },
      { row: 5, column: 25 },
    ],
    [
      { row: 4, column: 26 },
      { row: 4, column: 27 },
      { row: 5, column: 26 },
      { row: 5, column: 27 },
    ],
    [
      { row: 6, column: 1 },
      { row: 6, column: 2 },
      { row: 6, column: 3 },
      { row: 6, column: 4 },
      { row: 6, column: 5 },
      { row: 7, column: 1 },
      { row: 7, column: 2 },
      { row: 7, column: 3 },
      { row: 7, column: 4 },
      { row: 7, column: 5 },
      { row: 8, column: 1 },
      { row: 8, column: 2 },
      { row: 8, column: 3 },
      { row: 8, column: 4 },
      { row: 8, column: 5 },
      { row: 9, column: 1 },
      { row: 9, column: 2 },
      { row: 9, column: 3 },
      { row: 9, column: 4 },
      { row: 9, column: 5 },
      { row: 10, column: 1 },
      { row: 10, column: 2 },
      { row: 10, column: 3 },
      { row: 10, column: 4 },
      { row: 10, column: 5 },
    ],
    [
      { row: 6, column: 23 },
      { row: 6, column: 24 },
      { row: 6, column: 25 },
      { row: 6, column: 26 },
      { row: 6, column: 27 },
      { row: 7, column: 23 },
      { row: 7, column: 24 },
      { row: 7, column: 25 },
      { row: 7, column: 26 },
      { row: 7, column: 27 },
      { row: 8, column: 23 },
      { row: 8, column: 24 },
      { row: 8, column: 25 },
      { row: 8, column: 26 },
      { row: 8, column: 27 },
      { row: 9, column: 23 },
      { row: 9, column: 24 },
      { row: 9, column: 25 },
      { row: 9, column: 26 },
      { row: 9, column: 27 },
      { row: 10, column: 23 },
      { row: 10, column: 24 },
      { row: 10, column: 25 },
      { row: 10, column: 26 },
      { row: 10, column: 27 },
    ],
    [
      { row: 12, column: 1 },
      { row: 12, column: 2 },
      { row: 13, column: 1 },
      { row: 13, column: 2 },
    ],
    [
      { row: 12, column: 3 },
      { row: 13, column: 3 },
    ],
    [
      { row: 12, column: 4 },
      { row: 12, column: 5 },
      { row: 13, column: 4 },
      { row: 13, column: 5 },
    ],
    [
      { row: 14, column: 1 },
      { row: 14, column: 2 },
    ],
    [
      { row: 14, column: 4 },
      { row: 14, column: 5 },
    ],
    [
      { row: 15, column: 1 },
      { row: 15, column: 2 },
      { row: 16, column: 1 },
      { row: 16, column: 2 },
    ],
    [
      { row: 15, column: 3 },
      { row: 16, column: 3 },
    ],
    [
      { row: 15, column: 4 },
      { row: 15, column: 5 },
      { row: 16, column: 4 },
      { row: 16, column: 5 },
    ],
    [
      { row: 12, column: 23 },
      { row: 12, column: 24 },
      { row: 13, column: 23 },
      { row: 13, column: 24 },
    ],
    [
      { row: 12, column: 25 },
      { row: 13, column: 25 },
    ],
    [
      { row: 12, column: 26 },
      { row: 12, column: 27 },
      { row: 13, column: 26 },
      { row: 13, column: 27 },
    ],
    [
      { row: 14, column: 23 },
      { row: 14, column: 24 },
    ],
    [
      { row: 14, column: 26 },
      { row: 14, column: 27 },
    ],
    [
      { row: 15, column: 23 },
      { row: 15, column: 24 },
      { row: 16, column: 23 },
      { row: 16, column: 24 },
    ],
    [
      { row: 15, column: 25 },
      { row: 16, column: 25 },
    ],
    [
      { row: 15, column: 26 },
      { row: 15, column: 27 },
      { row: 16, column: 26 },
      { row: 16, column: 27 },
    ],
    [
      { row: 18, column: 1 },
      { row: 18, column: 2 },
      { row: 18, column: 3 },
      { row: 18, column: 4 },
      { row: 18, column: 5 },
      { row: 19, column: 1 },
      { row: 19, column: 2 },
      { row: 19, column: 3 },
      { row: 19, column: 4 },
      { row: 19, column: 5 },
      { row: 20, column: 1 },
      { row: 20, column: 2 },
      { row: 20, column: 3 },
      { row: 20, column: 4 },
      { row: 20, column: 5 },
      { row: 21, column: 1 },
      { row: 21, column: 2 },
      { row: 21, column: 3 },
      { row: 21, column: 4 },
      { row: 21, column: 5 },
      { row: 22, column: 1 },
      { row: 22, column: 2 },
      { row: 22, column: 3 },
      { row: 22, column: 4 },
      { row: 22, column: 5 },
    ],
    [
      { row: 18, column: 23 },
      { row: 18, column: 24 },
      { row: 18, column: 25 },
      { row: 18, column: 26 },
      { row: 18, column: 27 },
      { row: 19, column: 23 },
      { row: 19, column: 24 },
      { row: 19, column: 25 },
      { row: 19, column: 26 },
      { row: 19, column: 27 },
      { row: 20, column: 23 },
      { row: 20, column: 24 },
      { row: 20, column: 25 },
      { row: 20, column: 26 },
      { row: 20, column: 27 },
      { row: 21, column: 23 },
      { row: 21, column: 24 },
      { row: 21, column: 25 },
      { row: 21, column: 26 },
      { row: 21, column: 27 },
      { row: 22, column: 23 },
      { row: 22, column: 24 },
      { row: 22, column: 25 },
      { row: 22, column: 26 },
      { row: 22, column: 27 },
    ],
    [
      { row: 23, column: 1 },
      { row: 23, column: 2 },
      { row: 24, column: 1 },
      { row: 24, column: 2 },
    ],
    [
      { row: 23, column: 3 },
      { row: 24, column: 3 },
    ],
    [
      { row: 23, column: 4 },
      { row: 23, column: 5 },
      { row: 24, column: 4 },
      { row: 24, column: 5 },
    ],
    [
      { row: 25, column: 1 },
      { row: 25, column: 2 },
    ],
    [
      { row: 25, column: 4 },
      { row: 25, column: 5 },
    ],
    [
      { row: 26, column: 1 },
      { row: 26, column: 2 },
      { row: 27, column: 1 },
      { row: 27, column: 2 },
    ],
    [
      { row: 26, column: 3 },
      { row: 27, column: 3 },
    ],
    [
      { row: 26, column: 4 },
      { row: 26, column: 5 },
      { row: 27, column: 4 },
      { row: 27, column: 5 },
    ],
    [
      { row: 23, column: 6 },
      { row: 23, column: 7 },
      { row: 23, column: 8 },
      { row: 23, column: 9 },
      { row: 23, column: 10 },
      { row: 24, column: 6 },
      { row: 24, column: 7 },
      { row: 24, column: 8 },
      { row: 24, column: 9 },
      { row: 24, column: 10 },
      { row: 25, column: 6 },
      { row: 25, column: 7 },
      { row: 25, column: 8 },
      { row: 25, column: 9 },
      { row: 25, column: 10 },
      { row: 26, column: 6 },
      { row: 26, column: 7 },
      { row: 26, column: 8 },
      { row: 26, column: 9 },
      { row: 26, column: 10 },
      { row: 27, column: 6 },
      { row: 27, column: 7 },
      { row: 27, column: 8 },
      { row: 27, column: 9 },
      { row: 27, column: 10 },
    ],
    [
      { row: 23, column: 12 },
      { row: 23, column: 13 },
      { row: 24, column: 12 },
      { row: 24, column: 13 },
    ],
    [
      { row: 23, column: 14 },
      { row: 24, column: 14 },
    ],
    [
      { row: 23, column: 15 },
      { row: 23, column: 16 },
      { row: 24, column: 15 },
      { row: 24, column: 16 },
    ],
    [
      { row: 25, column: 12 },
      { row: 25, column: 13 },
    ],
    [
      { row: 25, column: 15 },
      { row: 25, column: 16 },
    ],
    [
      { row: 26, column: 12 },
      { row: 26, column: 13 },
      { row: 27, column: 12 },
      { row: 27, column: 13 },
    ],
    [
      { row: 26, column: 14 },
      { row: 27, column: 14 },
    ],
    [
      { row: 26, column: 15 },
      { row: 26, column: 16 },
      { row: 27, column: 15 },
      { row: 27, column: 16 },
    ],
    [
      { row: 23, column: 18 },
      { row: 23, column: 19 },
      { row: 23, column: 20 },
      { row: 23, column: 21 },
      { row: 23, column: 22 },
      { row: 24, column: 18 },
      { row: 24, column: 19 },
      { row: 24, column: 20 },
      { row: 24, column: 21 },
      { row: 24, column: 22 },
      { row: 25, column: 18 },
      { row: 25, column: 19 },
      { row: 25, column: 20 },
      { row: 25, column: 21 },
      { row: 25, column: 22 },
      { row: 26, column: 18 },
      { row: 26, column: 19 },
      { row: 26, column: 20 },
      { row: 26, column: 21 },
      { row: 26, column: 22 },
      { row: 27, column: 18 },
      { row: 27, column: 19 },
      { row: 27, column: 20 },
      { row: 27, column: 21 },
      { row: 27, column: 22 },
    ],
    [
      { row: 23, column: 23 },
      { row: 23, column: 24 },
      { row: 24, column: 23 },
      { row: 24, column: 24 },
    ],
    [
      { row: 23, column: 25 },
      { row: 24, column: 25 },
    ],
    [
      { row: 23, column: 26 },
      { row: 23, column: 27 },
      { row: 24, column: 26 },
      { row: 24, column: 27 },
    ],
    [
      { row: 25, column: 23 },
      { row: 25, column: 24 },
    ],
    [
      { row: 25, column: 26 },
      { row: 25, column: 27 },
    ],
    [
      { row: 26, column: 23 },
      { row: 26, column: 24 },
      { row: 27, column: 23 },
      { row: 27, column: 24 },
    ],
    [
      { row: 26, column: 25 },
      { row: 27, column: 25 },
    ],
    [
      { row: 26, column: 26 },
      { row: 26, column: 27 },
      { row: 27, column: 26 },
      { row: 27, column: 27 },
    ],
    [
      { row: 7, column: 7 },
      { row: 7, column: 8 },
      { row: 8, column: 7 },
      { row: 8, column: 8 },
    ],
    [
      { row: 7, column: 9 },
      { row: 8, column: 9 },
    ],
    [
      { row: 7, column: 10 },
      { row: 7, column: 11 },
      { row: 8, column: 10 },
      { row: 8, column: 11 },
    ],
    [
      { row: 9, column: 7 },
      { row: 9, column: 8 },
    ],
    [{ row: 9, column: 9 }],
    [
      { row: 9, column: 10 },
      { row: 9, column: 11 },
    ],
    [
      { row: 10, column: 7 },
      { row: 10, column: 8 },
      { row: 11, column: 7 },
      { row: 11, column: 8 },
    ],
    [
      { row: 10, column: 9 },
      { row: 11, column: 9 },
    ],
    [
      { row: 10, column: 10 },
      { row: 10, column: 11 },
      { row: 11, column: 10 },
      { row: 11, column: 11 },
    ],
    [{ row: 7, column: 12 }],
    [{ row: 7, column: 16 }],
    [{ row: 9, column: 14 }],
    [{ row: 11, column: 12 }],
    [{ row: 11, column: 16 }],
    [
      { row: 7, column: 17 },
      { row: 7, column: 18 },
      { row: 8, column: 17 },
      { row: 8, column: 18 },
    ],
    [
      { row: 7, column: 19 },
      { row: 8, column: 19 },
    ],
    [
      { row: 7, column: 20 },
      { row: 7, column: 21 },
      { row: 8, column: 20 },
      { row: 8, column: 21 },
    ],
    [
      { row: 9, column: 17 },
      { row: 9, column: 18 },
    ],
    [{ row: 9, column: 19 }],
    [
      { row: 9, column: 20 },
      { row: 9, column: 21 },
    ],
    [
      { row: 10, column: 17 },
      { row: 10, column: 18 },
      { row: 11, column: 17 },
      { row: 11, column: 18 },
    ],
    [
      { row: 10, column: 19 },
      { row: 11, column: 19 },
    ],
    [
      { row: 10, column: 20 },
      { row: 10, column: 21 },
      { row: 11, column: 20 },
      { row: 11, column: 21 },
    ],
    [
      { row: 12, column: 7 },
      { row: 12, column: 8 },
      { row: 12, column: 9 },
      { row: 12, column: 10 },
      { row: 12, column: 11 },
      { row: 13, column: 7 },
      { row: 13, column: 8 },
      { row: 13, column: 9 },
      { row: 13, column: 10 },
      { row: 13, column: 11 },
      { row: 14, column: 7 },
      { row: 14, column: 8 },
      { row: 14, column: 9 },
      { row: 14, column: 10 },
      { row: 14, column: 11 },
      { row: 15, column: 7 },
      { row: 15, column: 8 },
      { row: 15, column: 9 },
      { row: 15, column: 10 },
      { row: 15, column: 11 },
      { row: 16, column: 7 },
      { row: 16, column: 8 },
      { row: 16, column: 9 },
      { row: 16, column: 10 },
      { row: 16, column: 11 },
    ],
    [
      { row: 12, column: 12 },
      { row: 12, column: 13 },
      { row: 13, column: 12 },
      { row: 13, column: 13 },
    ],
    [
      { row: 12, column: 14 },
      { row: 13, column: 14 },
    ],
    [
      { row: 12, column: 15 },
      { row: 12, column: 16 },
      { row: 13, column: 15 },
      { row: 13, column: 16 },
    ],
    [
      { row: 14, column: 12 },
      { row: 14, column: 13 },
    ],
    [
      { row: 14, column: 15 },
      { row: 14, column: 16 },
    ],
    [
      { row: 15, column: 12 },
      { row: 15, column: 13 },
      { row: 16, column: 12 },
      { row: 16, column: 13 },
    ],
    [
      { row: 15, column: 14 },
      { row: 16, column: 14 },
    ],
    [
      { row: 15, column: 15 },
      { row: 15, column: 16 },
      { row: 16, column: 15 },
      { row: 16, column: 16 },
    ],
    [
      { row: 12, column: 17 },
      { row: 12, column: 18 },
      { row: 12, column: 19 },
      { row: 12, column: 20 },
      { row: 12, column: 21 },
      { row: 13, column: 17 },
      { row: 13, column: 18 },
      { row: 13, column: 19 },
      { row: 13, column: 20 },
      { row: 13, column: 21 },
      { row: 14, column: 17 },
      { row: 14, column: 18 },
      { row: 14, column: 19 },
      { row: 14, column: 20 },
      { row: 14, column: 21 },
      { row: 15, column: 17 },
      { row: 15, column: 18 },
      { row: 15, column: 19 },
      { row: 15, column: 20 },
      { row: 15, column: 21 },
      { row: 16, column: 17 },
      { row: 16, column: 18 },
      { row: 16, column: 19 },
      { row: 16, column: 20 },
      { row: 16, column: 21 },
    ],
    [
      { row: 17, column: 7 },
      { row: 17, column: 8 },
      { row: 18, column: 7 },
      { row: 18, column: 8 },
    ],
    [{ row: 17, column: 9 }],
    [{ row: 18, column: 9 }],
    [
      { row: 17, column: 10 },
      { row: 17, column: 11 },
      { row: 18, column: 10 },
      { row: 18, column: 11 },
    ],
    [{ row: 19, column: 7 }],
    [{ row: 19, column: 8 }],
    [{ row: 19, column: 9 }],
    [{ row: 19, column: 10 }],
    [{ row: 19, column: 11 }],
    [
      { row: 20, column: 7 },
      { row: 20, column: 8 },
      { row: 21, column: 7 },
      { row: 21, column: 8 },
    ],
    [{ row: 20, column: 9 }],
    [{ row: 21, column: 9 }],
    [
      { row: 20, column: 10 },
      { row: 20, column: 11 },
      { row: 21, column: 10 },
      { row: 21, column: 11 },
    ],
    [
      { row: 17, column: 12 },
      { row: 17, column: 13 },
      { row: 18, column: 12 },
      { row: 18, column: 13 },
    ],
    [{ row: 17, column: 14 }],
    [
      { row: 17, column: 15 },
      { row: 17, column: 16 },
      { row: 18, column: 15 },
      { row: 18, column: 16 },
    ],
    [{ row: 19, column: 12 }],
    [{ row: 19, column: 14 }],
    [{ row: 19, column: 16 }],
    [
      { row: 20, column: 12 },
      { row: 20, column: 13 },
      { row: 21, column: 12 },
      { row: 21, column: 13 },
    ],
    [{ row: 21, column: 14 }],
    [
      { row: 20, column: 15 },
      { row: 20, column: 16 },
      { row: 21, column: 15 },
      { row: 21, column: 16 },
    ],
    [
      { row: 17, column: 17 },
      { row: 17, column: 18 },
      { row: 18, column: 17 },
      { row: 18, column: 18 },
    ],
    [{ row: 17, column: 19 }],
    [{ row: 18, column: 19 }],
    [
      { row: 17, column: 20 },
      { row: 17, column: 21 },
      { row: 18, column: 20 },
      { row: 18, column: 21 },
    ],
    [{ row: 19, column: 17 }],
    [{ row: 19, column: 18 }],
    [{ row: 19, column: 19 }],
    [{ row: 19, column: 20 }],
    [{ row: 19, column: 21 }],
    [
      { row: 20, column: 17 },
      { row: 20, column: 18 },
      { row: 21, column: 17 },
      { row: 21, column: 18 },
    ],
    [{ row: 20, column: 19 }],
    [{ row: 21, column: 19 }],
    [
      { row: 20, column: 20 },
      { row: 20, column: 21 },
      { row: 21, column: 20 },
      { row: 21, column: 21 },
    ],
  ],
  walls: [
    [
      { row: 22, column: 11 },
      { row: 22, column: 10 },
      { row: 22, column: 9 },
      { row: 22, column: 8 },
      { row: 22, column: 7 },
      { row: 22, column: 6 },
      { row: 21, column: 6 },
      { row: 20, column: 6 },
      { row: 19, column: 6 },
      { row: 18, column: 6 },
      { row: 17, column: 6 },
      { row: 16, column: 6 },
      { row: 15, column: 6 },
      { row: 14, column: 6 },
      { row: 13, column: 6 },
      { row: 12, column: 6 },
      { row: 11, column: 6 },
      { row: 10, column: 6 },
      { row: 9, column: 6 },
      { row: 8, column: 6 },
      { row: 7, column: 6 },
      { row: 6, column: 6 },
      { row: 6, column: 7 },
      { row: 6, column: 8 },
      { row: 6, column: 9 },
      { row: 6, column: 10 },
      { row: 6, column: 11 },
      { row: 6, column: 12 },
      { row: 6, column: 13 },
      { row: 6, column: 14 },
      { row: 6, column: 15 },
      { row: 6, column: 16 },
      { row: 6, column: 17 },
      { row: 6, column: 18 },
      { row: 6, column: 19 },
      { row: 6, column: 20 },
      { row: 6, column: 21 },
      { row: 6, column: 22 },
      { row: 7, column: 22 },
      { row: 8, column: 22 },
      { row: 9, column: 22 },
      { row: 10, column: 22 },
      { row: 11, column: 22 },
      { row: 12, column: 22 },
      { row: 13, column: 22 },
      { row: 14, column: 22 },
      { row: 15, column: 22 },
      { row: 16, column: 22 },
      { row: 17, column: 22 },
      { row: 18, column: 22 },
      { row: 19, column: 22 },
      { row: 20, column: 22 },
      { row: 21, column: 22 },
      { row: 22, column: 22 },
      { row: 22, column: 21 },
      { row: 22, column: 20 },
      { row: 22, column: 19 },
      { row: 22, column: 18 },
      { row: 22, column: 17 },
    ],
  ],
  gates: [
    [
      { row: 22, column: 12 },
      { row: 22, column: 13 },
      { row: 22, column: 14 },
      { row: 22, column: 15 },
      { row: 22, column: 16 },
    ],
  ],
};
