import { BoardConfig } from "./models";

// Oldest Game
export const oldestGame: BoardConfig = {
  rows: 11,
  columns: 10,
  target: [
    { row: 10, column: 9 },
    { row: 10, column: 10 },
    { row: 11, column: 9 },
    { row: 11, column: 10 },
  ],
  masterBlock: [
    { row: 4, column: 5 },
    { row: 4, column: 6 },
    { row: 5, column: 5 },
    { row: 5, column: 6 },
  ],
  blocks: [
    [
      { row: 4, column: 4 },
      { row: 5, column: 4 },
    ],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [{ row: 6, column: 4 }],
    [{ row: 6, column: 5 }],
    [{ row: 6, column: 6 }],
    [{ row: 6, column: 7 }],
    [{ row: 7, column: 4 }],
    [{ row: 7, column: 5 }],
    [{ row: 7, column: 6 }],
    [{ row: 7, column: 7 }],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 7 }],
  ],
  walls: [
    [
      { row: 9, column: 4 },
      { row: 9, column: 3 },
      { row: 8, column: 3 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 3, column: 4 },
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
      { row: 6, column: 8 },
      { row: 7, column: 8 },
      { row: 8, column: 8 },
      { row: 9, column: 8 },
      { row: 9, column: 7 },
    ],
  ],
  gates: [
    [
      { row: 9, column: 5 },
      { row: 9, column: 6 },
    ],
  ],
};

export const oldestGame2: BoardConfig = {
  rows: 11,
  columns: 10,
  target: [
    { row: 10, column: 9 },
    { row: 10, column: 10 },
    { row: 11, column: 9 },
    { row: 11, column: 10 },
  ],
  masterBlock: [
    { row: 4, column: 5 },
    { row: 4, column: 6 },
    { row: 5, column: 5 },
    { row: 5, column: 6 },
  ],
  blocks: [
    [
      { row: 4, column: 4 },
      { row: 5, column: 4 },
    ],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [
      { row: 6, column: 4 },
      { row: 7, column: 4 },
    ],
    [{ row: 6, column: 5 }],
    [{ row: 6, column: 6 }],
    [{ row: 6, column: 7 }],
    [{ row: 7, column: 5 }],
    [{ row: 7, column: 6 }],
    [{ row: 7, column: 7 }],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 7 }],
  ],
  walls: [
    [
      { row: 9, column: 4 },
      { row: 9, column: 3 },
      { row: 8, column: 3 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 3, column: 4 },
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
      { row: 6, column: 8 },
      { row: 7, column: 8 },
      { row: 8, column: 8 },
      { row: 9, column: 8 },
      { row: 9, column: 7 },
    ],
  ],
  gates: [
    [
      { row: 9, column: 5 },
      { row: 9, column: 6 },
    ],
  ],
};

export const oldestGame3: BoardConfig = {
  rows: 11,
  columns: 10,
  target: [
    { row: 10, column: 9 },
    { row: 10, column: 10 },
    { row: 11, column: 9 },
    { row: 11, column: 10 },
  ],
  masterBlock: [
    { row: 4, column: 5 },
    { row: 4, column: 6 },
    { row: 5, column: 5 },
    { row: 5, column: 6 },
  ],
  blocks: [
    [
      { row: 4, column: 4 },
      { row: 5, column: 4 },
    ],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [{ row: 6, column: 4 }],
    [
      { row: 6, column: 5 },
      { row: 6, column: 6 },
    ],
    [{ row: 6, column: 7 }],
    [{ row: 7, column: 4 }],
    [{ row: 7, column: 5 }],
    [{ row: 7, column: 6 }],
    [{ row: 7, column: 7 }],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 7 }],
  ],
  walls: [
    [
      { row: 9, column: 4 },
      { row: 9, column: 3 },
      { row: 8, column: 3 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 3, column: 4 },
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
      { row: 6, column: 8 },
      { row: 7, column: 8 },
      { row: 8, column: 8 },
      { row: 9, column: 8 },
      { row: 9, column: 7 },
    ],
  ],
  gates: [
    [
      { row: 9, column: 5 },
      { row: 9, column: 6 },
    ],
  ],
};

export const oldestGame4: BoardConfig = {
  rows: 11,
  columns: 10,
  target: [
    { row: 10, column: 9 },
    { row: 10, column: 10 },
    { row: 11, column: 9 },
    { row: 11, column: 10 },
  ],
  masterBlock: [
    { row: 4, column: 5 },
    { row: 4, column: 6 },
    { row: 5, column: 5 },
    { row: 5, column: 6 },
  ],
  blocks: [
    [
      { row: 4, column: 4 },
      { row: 5, column: 4 },
    ],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [
      { row: 6, column: 4 },
      { row: 7, column: 4 },
    ],
    [{ row: 6, column: 5 }],
    [{ row: 6, column: 6 }],
    [
      { row: 6, column: 7 },
      { row: 7, column: 7 },
    ],
    [{ row: 7, column: 5 }],
    [{ row: 7, column: 6 }],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 7 }],
  ],
  walls: [
    [
      { row: 9, column: 4 },
      { row: 9, column: 3 },
      { row: 8, column: 3 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 3, column: 4 },
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
      { row: 6, column: 8 },
      { row: 7, column: 8 },
      { row: 8, column: 8 },
      { row: 9, column: 8 },
      { row: 9, column: 7 },
    ],
  ],
  gates: [
    [
      { row: 9, column: 5 },
      { row: 9, column: 6 },
    ],
  ],
};

export const oldestGame5: BoardConfig = {
  rows: 11,
  columns: 10,
  target: [
    { row: 10, column: 9 },
    { row: 10, column: 10 },
    { row: 11, column: 9 },
    { row: 11, column: 10 },
  ],
  masterBlock: [
    { row: 4, column: 5 },
    { row: 4, column: 6 },
    { row: 5, column: 5 },
    { row: 5, column: 6 },
  ],
  blocks: [
    [
      { row: 4, column: 4 },
      { row: 5, column: 4 },
    ],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [
      { row: 6, column: 4 },
      { row: 7, column: 4 },
    ],
    [
      { row: 6, column: 5 },
      { row: 6, column: 6 },
    ],
    [{ row: 6, column: 7 }],
    [{ row: 7, column: 5 }],
    [{ row: 7, column: 6 }],
    [{ row: 7, column: 7 }],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 7 }],
  ],
  walls: [
    [
      { row: 9, column: 4 },
      { row: 9, column: 3 },
      { row: 8, column: 3 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 3, column: 4 },
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
      { row: 6, column: 8 },
      { row: 7, column: 8 },
      { row: 8, column: 8 },
      { row: 9, column: 8 },
      { row: 9, column: 7 },
    ],
  ],
  gates: [
    [
      { row: 9, column: 5 },
      { row: 9, column: 6 },
    ],
  ],
};

export const oldestGame6: BoardConfig = {
  rows: 11,
  columns: 10,
  target: [
    { row: 10, column: 9 },
    { row: 10, column: 10 },
    { row: 11, column: 9 },
    { row: 11, column: 10 },
  ],
  masterBlock: [
    { row: 4, column: 5 },
    { row: 4, column: 6 },
    { row: 5, column: 5 },
    { row: 5, column: 6 },
  ],
  blocks: [
    [
      { row: 4, column: 4 },
      { row: 5, column: 4 },
    ],
    [
      { row: 4, column: 7 },
      { row: 5, column: 7 },
    ],
    [
      { row: 6, column: 4 },
      { row: 7, column: 4 },
    ],
    [
      { row: 6, column: 5 },
      { row: 6, column: 6 },
    ],
    [
      { row: 6, column: 7 },
      { row: 7, column: 7 },
    ],
    [{ row: 7, column: 5 }],
    [{ row: 7, column: 6 }],
    [{ row: 8, column: 4 }],
    [{ row: 8, column: 7 }],
  ],
  walls: [
    [
      { row: 9, column: 4 },
      { row: 9, column: 3 },
      { row: 8, column: 3 },
      { row: 7, column: 3 },
      { row: 6, column: 3 },
      { row: 5, column: 3 },
      { row: 4, column: 3 },
      { row: 3, column: 3 },
      { row: 3, column: 4 },
      { row: 3, column: 5 },
      { row: 3, column: 6 },
      { row: 3, column: 7 },
      { row: 3, column: 8 },
      { row: 4, column: 8 },
      { row: 5, column: 8 },
      { row: 6, column: 8 },
      { row: 7, column: 8 },
      { row: 8, column: 8 },
      { row: 9, column: 8 },
      { row: 9, column: 7 },
    ],
  ],
  gates: [
    [
      { row: 9, column: 5 },
      { row: 9, column: 6 },
    ],
  ],
};

export const agatka: BoardConfig = {
  rows: 9,
  columns: 11,
  target: [
    { row: 8, column: 1 },
    { row: 8, column: 2 },
    { row: 9, column: 1 },
  ],
  masterBlock: [
    { row: 4, column: 4 },
    { row: 4, column: 5 },
    { row: 5, column: 4 },
  ],
  blocks: [
    [{ row: 1, column: 1 }],
    [{ row: 2, column: 1 }],
    [
      { row: 1, column: 2 },
      { row: 1, column: 3 },
      { row: 1, column: 4 },
      { row: 1, column: 5 },
      { row: 2, column: 2 },
      { row: 2, column: 3 },
      { row: 2, column: 4 },
      { row: 2, column: 5 },
    ],
    [
      { row: 1, column: 6 },
      { row: 1, column: 7 },
      { row: 1, column: 8 },
      { row: 1, column: 9 },
      { row: 1, column: 10 },
    ],
    [{ row: 1, column: 11 }],
    [
      { row: 2, column: 6 },
      { row: 2, column: 7 },
      { row: 2, column: 8 },
    ],
    [
      { row: 2, column: 10 },
      { row: 2, column: 11 },
    ],
    [{ row: 3, column: 10 }],
    [
      { row: 5, column: 1 },
      { row: 6, column: 1 },
    ],
    [
      { row: 3, column: 2 },
      { row: 4, column: 2 },
      { row: 5, column: 2 },
      { row: 6, column: 2 },
      { row: 7, column: 2 },
      { row: 8, column: 2 },
      { row: 9, column: 2 },
    ],
    [
      { row: 9, column: 3 },
      { row: 9, column: 4 },
    ],
  ],
  walls: [
    [
      { row: 3, column: 7 },
      { row: 3, column: 6 },
      { row: 3, column: 5 },
      { row: 3, column: 4 },
      { row: 3, column: 3 },
      { row: 4, column: 3 },
      { row: 5, column: 3 },
      { row: 6, column: 3 },
      { row: 7, column: 3 },
      { row: 7, column: 4 },
      { row: 7, column: 5 },
      { row: 7, column: 6 },
      { row: 7, column: 7 },
      { row: 7, column: 8 },
      { row: 7, column: 9 },
      { row: 6, column: 9 },
      { row: 5, column: 9 },
    ],
  ],
  gates: [
    [
      { row: 3, column: 8 },
      { row: 3, column: 9 },
      { row: 4, column: 9 },
    ],
  ],
};
